[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin augment-command -- enter"
desc = "Enter the child directory, or open the file"
[[mgr.prepend_keymap]]
on = "<S-k>" 
run = "plugin augment-command -- parent_arrow -1"
[[mgr.prepend_keymap]]
on = "<S-j>" 
run = "plugin augment-command -- parent_arrow 1"
[[mgr.prepend_keymap]]
on = "<C-j>" 
run = "seek 5"
[[mgr.prepend_keymap]]
on = "<C-k>" 
run = "seek -5"
[[mgr.prepend_keymap]]
on = "t" 
run = "plugin augment-command -- tab_create"
[[mgr.prepend_keymap]]
on = "q" 
run = "quit --no-cwd-file"
[[mgr.prepend_keymap]]
on = "Q" 
run = "quit"
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
